name: Documentation

on:
  push:
    branches: 
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Remove contents in Wiki
        working-directory: wiki
        run: ls -A1 | grep -v '.git' | xargs rm -r
      
      - name: Copy Wiki from Docs folder
        run: cp -r ./docs/. ./wiki

      - name: Set Repository in Docs
        shell: bash
        run: |
          cd wiki
          find . | grep .md | xargs sed -i "s|<<REPO>>|${{ github.repository }}|g"
          
      - name: Deploy 🚀
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: wiki