name: Update Dependencies and Update Versions

on:
  workflow_call:
    inputs:
        with-submodules:
          description: "Clone repository with its submodules"
          type: boolean
          required: false
          default: false
        create-tag:
          description: "Indicator if a tag should be created"
          type: boolean
          required: false
          default: true
        runs-on:
          description: "Tag for the runner to use in the main job."
          type: string
          required: false
          default: "ubuntu-latest"
        auto-digit:
          description: "The digit to be automatically incremented. E.g., Major, Minor, or Patch"
          type: string
          required: false
          default: "Patch"

    secrets:
      PAT:
        required: true

jobs:  
  build:
    name: "Check for Updates"
    runs-on: ${{ inputs.runs-on }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: ${{ inputs.with-submodules }}
        persist-credentials: false
        fetch-depth: 0

    - uses: joshlong/java-version-export-github-action@v28
      id: jve

    - uses: actions/setup-java@v4
      with:
        java-version: ${{ steps.jve.outputs.java_major_version }}
        distribution: 'temurin'
        cache: 'maven'

    - name: Update Dependencies
      shell: bash
      run: |
        mvn -U -B versions:update-parent versions:update-properties versions:update-parent versions:update-child-modules versions:use-latest-releases -DgenerateBackupPoms=false | tee /tmp/updates-raw.txt
        mvn -U -B verify
        echo 'Auto-Update Dependencies' > /tmp/updates.txt
        cat /tmp/updates-raw.txt | grep 'Updat' | sort | uniq | cut -d ' ' -f 2- >> /tmp/updates.txt || true
        echo 'Setting commit message to ..'
        cat /tmp/updates.txt

    - name: Check if there are changes
      id: changes
      run: echo "changed=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT

    - name: Commit Changes of Versions
      if: steps.changes.outputs.changed != 0
      shell: bash
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add . && git commit -F /tmp/updates.txt

    - name: New Release if there were Updates
      # This step will only for for single module projects or projects that use the revision property
      shell: bash
      if: ${{ steps.changes.outputs.changed != 0 && inputs.create-tag }}
      run: |
        # Check that workflow has only one "uses" in its file
        if [ $(grep -c "uses:" ${{github.event.workflow}}) -ne 1 ]; then
          echo "Workflow has more than one 'uses' in its file. Skipping ..."
          exit 1
        fi
        WORKFLOW_REPO=$(cat ${{github.event.workflow}} | grep "uses:" | awk '{print $2}' | cut -d '/' -f 1,2)
        echo "Workflow repo is $WORKFLOW_REPO"

        # Download version update script to tmp directory
        curl -s https://raw.githubusercontent.com/$WORKFLOW_REPO/main/scripts/maven-version-update.sh > /tmp/maven-version-update.sh
        chmod +x /tmp/maven-version-update.sh
        echo "######### Content of maven-version-update.sh #########"
        cat /tmp/maven-version-update.sh
        echo "######################################################"
        echo "######### Running maven-version-update.sh ###########"
        AUTO_DIGIT=${{ inputs.auto-digit }} bash /tmp/maven-version-update.sh  
        echo "######################################################"
        
    - name: Push Changes
      uses: ad-m/github-push-action@master
      if: steps.changes.outputs.changed != 0
      with:
        # See https://github.com/orgs/community/discussions/25702 and https://github.com/orgs/community/discussions/26220
        github_token: ${{ secrets.PAT }}
        branch: ${{ github.ref }}
        tags: ${{ inputs.create-tag }}
