name: SonarCloud for Maven Projects

on:
  workflow_call:
    inputs:
        with-submodules:
          description: "Clone repository with its submodules"
          type: boolean
          required: false
          default: false
        runs-on:
          description: "Tag for the runner to use in the main job."
          type: string
          required: false
          default: "ubuntu-latest"
    secrets:
      SONAR_TOKEN:
        required: true
          
jobs:      
  build:
    name: "SonarCloud Scan"
    runs-on: ${{ inputs.runs-on }}
    if: ${{ github.actor != 'dependabot[bot]' }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: ${{ inputs.with-submodules }}
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

    - uses: joshlong/java-version-export-github-action@v28
      id: jve

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ steps.jve.outputs.java_major_version }}
        cache: 'maven'
                
    - name: Build and Analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file pom.xml
